### PR TITLE
support max connection count over grpc

### PR DESCRIPTION
**Pull request by andymck**
dependant PR: https://github.com/novalabsxyz/acceptor_pool/pull/3

Adds support for a max count of grpc connections.  Once exceeded new connections will be terminated.
This is a cheap attempt to prevent validators being overloaded with grpc connections, the extend to which it will help is unknown at this point as it does not prevent connections hitting the socket, it only terminates them at the earliest opportunity.  

Obviously limiting connections at the boundaries would be a much more robust and performant solution but that option is not available.

### CODE REVIEW

**Comment by Vagabond** [comment]
Should we look at connection *rate* as well? if you have 1,000 max connections but they're all reconnecting every 0.1 seconds, you still might get a lot of load?

**Comment by Vagabond** [comment]
> Should we look at connection _rate_ as well? if you have 1,000 max connections but they're all reconnecting every 0.1 seconds, you still might get a lot of load?

maybe we should use something like https://github.com/lambdaclass/throttle so we can express a connection rate limit as well?

**Comment by andymck** [comment]
It could certainly be helpful

**Comment by Vagabond** [comment]
Tests seem pretty broken, but that seems pre-existing.

```
src/grpcbox_pool.erl
Line 13 Column 5: Call to missing or unexported function acceptor_pool:start_link/4
```

**Comment by andymck** [comment]
> Tests seem pretty broken, but that seems pre-existing.
> 
> ```
> src/grpcbox_pool.erl
> Line 13 Column 5: Call to missing or unexported function acceptor_pool:start_link/4
> ```

Ah that was some late refactoring, fixed here:  8cdceb9815e41bfa71416a2ca2c046fb835b9c9d

**Review by jeffgrunewald — APPROVED** [review]

**Pull request merged**
